const START_FETCH_DATA = "START_FETCH_DATA";
const FINISH_FETCH_DATA = "FINISH_FETCH_DATA";
const ERROR_WHILE_FETCH_DATA = "ERROR_WHILE_FETCH_DATA";
const ONCHANGE_CATEGORIES = "ONCHANGE_CATEGORIES";
const ONCHANGE_DIFICULTIES = "ONCHANGE_DIFICULTIES";

export {
  START_FETCH_DATA,
  FINISH_FETCH_DATA,
  ERROR_WHILE_FETCH_DATA,
  ONCHANGE_CATEGORIES,
  ONCHANGE_DIFICULTIES,
};
